/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LpSlugRouteImport } from './routes/lp.$slug'
import { Route as AdminPagesRouteImport } from './routes/admin.pages'
import { Route as ApiPublicCronProcessBriefsRouteImport } from './routes/api/public/cron-process-briefs'
import { Route as AdminPagesSlugRouteImport } from './routes/admin.pages.$slug'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LpSlugRoute = LpSlugRouteImport.update({
  id: '/lp/$slug',
  path: '/lp/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicCronProcessBriefsRoute =
  ApiPublicCronProcessBriefsRouteImport.update({
    id: '/api/public/cron-process-briefs',
    path: '/api/public/cron-process-briefs',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminPagesSlugRoute = AdminPagesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdminPagesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/pages': typeof AdminPagesRouteWithChildren
  '/lp/$slug': typeof LpSlugRoute
  '/admin/pages/$slug': typeof AdminPagesSlugRoute
  '/api/public/cron-process-briefs': typeof ApiPublicCronProcessBriefsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/pages': typeof AdminPagesRouteWithChildren
  '/lp/$slug': typeof LpSlugRoute
  '/admin/pages/$slug': typeof AdminPagesSlugRoute
  '/api/public/cron-process-briefs': typeof ApiPublicCronProcessBriefsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/pages': typeof AdminPagesRouteWithChildren
  '/lp/$slug': typeof LpSlugRoute
  '/admin/pages/$slug': typeof AdminPagesSlugRoute
  '/api/public/cron-process-briefs': typeof ApiPublicCronProcessBriefsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/pages'
    | '/lp/$slug'
    | '/admin/pages/$slug'
    | '/api/public/cron-process-briefs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/pages'
    | '/lp/$slug'
    | '/admin/pages/$slug'
    | '/api/public/cron-process-briefs'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/pages'
    | '/lp/$slug'
    | '/admin/pages/$slug'
    | '/api/public/cron-process-briefs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LpSlugRoute: typeof LpSlugRoute
  ApiPublicCronProcessBriefsRoute: typeof ApiPublicCronProcessBriefsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp/$slug': {
      id: '/lp/$slug'
      path: '/lp/$slug'
      fullPath: '/lp/$slug'
      preLoaderRoute: typeof LpSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/cron-process-briefs': {
      id: '/api/public/cron-process-briefs'
      path: '/api/public/cron-process-briefs'
      fullPath: '/api/public/cron-process-briefs'
      preLoaderRoute: typeof ApiPublicCronProcessBriefsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pages/$slug': {
      id: '/admin/pages/$slug'
      path: '/$slug'
      fullPath: '/admin/pages/$slug'
      preLoaderRoute: typeof AdminPagesSlugRouteImport
      parentRoute: typeof AdminPagesRoute
    }
  }
}

interface AdminPagesRouteChildren {
  AdminPagesSlugRoute: typeof AdminPagesSlugRoute
}

const AdminPagesRouteChildren: AdminPagesRouteChildren = {
  AdminPagesSlugRoute: AdminPagesSlugRoute,
}

const AdminPagesRouteWithChildren = AdminPagesRoute._addFileChildren(
  AdminPagesRouteChildren,
)

interface AdminRouteChildren {
  AdminPagesRoute: typeof AdminPagesRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminPagesRoute: AdminPagesRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LpSlugRoute: LpSlugRoute,
  ApiPublicCronProcessBriefsRoute: ApiPublicCronProcessBriefsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
